name: update_progress

on:
  push:
    branches: master

  jobs:
    update:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Update progress bar
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install numpy matplotlib seaborn
          ./update_progress.sh
